# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: feef7da4a0961b9e993d161ae425f0dd48ebe80937859f38bb2520901428fd8bd7d0d08507ed3a27bef731a24c983f04c3806372ba71c079ef48ba4ae3bcb675

test:
  secret_key_base: ae41801490bd201c1bf6f930bcc0164cfbab7dde6ddb738fdaa0a82349c4107d234e545554a947a533a7d997b58f0fa8a8fbbcc5a719713ba9235dd3915f91af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
